version: "3.9"

services:
  client:
    container_name: kaspanodemon_client
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"

  server:
    container_name: kaspanodemon_server
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
    - "8124:3000"
